### ISSUE TITLE
With the aks limitations and what we need out of it, is istio usable / worth it right now?

### ISSUE THREAD

**Issue by Phanoix** [gctools-outilsgc/Kubernetes-config#26]
Test various possible configurations, see if any are worth it right now or if we should wait for aks, istio to mature more.

**Comment by Phanoix** [comment]
Linkerd seems to fit better currently.

**Comment by wmorgan** [comment]
Great to hear it. If you get stuck on anything, please feel free to hop into [slack.linkerd.io](https://slack.linkerd.io)!
